# A short, descriptive name of this building block collection
name: OGC Building Blocks tutorial examples repository

# Short abstract for this collection (optional)
abstract: |
  A set of building blocks introducing capabilities, as a sequence of exercises.
# Description for this collection (optional)
description: |
  Follow the instructions in the "About section" of each building block, starting with the Overview to orient yourself.
  
# Customize the following prefix (will be prepended to the path of the building blocks):
identifier-prefix: ogc.bbr.tutorial.

# List of imports ("default" is an alias for the main OGC Building Blocks Register)
imports:
  - default
#  - https://ogcincubator.github.io/topo-feature/build/register.json

# SPARQL configuration (optional)
#   Authentication can be set through the sparql_username and sparql_password GitHub Workflow inputs
#   (see .github/workflow/process-bblocks.yml)
#
# sparql:
#   push: https://example.com/gsp           # SPARQL Graph Store Protocol endpoint for uploading data
#   graph: https://my.bblocks.example.com/  # SPARQL Graph where data will be uploaded
#                                           #  if left empty, the base URL for the publication will be used
#   query: https://example.com/sparql       # SPARQL query endpoint where data will be available
