$schema: https://json-schema.org/draft/2020-12/schema
description: Profile of Exercise 2 that overrides its inherited "b" binding
allOf:
  - $ref: bblocks://ogc.bbr.tutorial.exercise2
  - type: object
    properties:
      b:
        type: number
